/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "gestionRFC.h"

nodo_usuario vectorDeUsuario[5];
int consultaVector(int cedula);
int posUsuario=0;
char vocal_interna(char apellido[30]);

bool_t *
registrarusuariosistema_1_svc(nodo_usuario *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	printf("\n --------Invocando a registrar Usuario\n");
	if (posUsuario<4)
	{
		vectorDeUsuario[posUsuario]=*argp;
		result = TRUE;
		posUsuario++;
		printf("\n --------Registrando Usuario\n");
	}
	else {
		printf("\n --------Cantidad maxima de registros alcanzada\n");
		result=FALSE;
	}	
	return &result;
}

char **
calcularrfc_1_svc(int *argp, struct svc_req *rqstp)
{
	static char * result;
	int cedula = *argp;
    
    int pos = consultaVector(*argp);
    printf("\n --------Identificador a buscar\n");
    if (pos!=-1){
        printf("Nombre completo: %s %s %s\n", vectorDeUsuario[pos].nombre, vectorDeUsuario[pos].apellidoPto, vectorDeUsuario[pos].apellidoMto);
        printf("Cedula: %d\n", vectorDeUsuario[pos].cedula);
        printf("Nombre de usuario: %s\n", vectorDeUsuario[pos].username);
        printf("Contraseña: %s\n", vectorDeUsuario[pos].password);
        printf("Fecha de nacimiento: %d / %d / %d\n", vectorDeUsuario[pos].dia_nac, vectorDeUsuario[pos].mes_nac, vectorDeUsuario[pos].anio_nac);
        //vectorDeUsuario[pos];
        vectorDeUsuario[pos].rfc[0] = vectorDeUsuario[pos].apellidoPto[0];
        vectorDeUsuario[pos].rfc[1] = vocal_interna(vectorDeUsuario[pos].apellidoPto);
        if(vectorDeUsuario[pos].apellidoMto[0]!='X'){
            vectorDeUsuario[pos].rfc[2] = vectorDeUsuario[pos].apellidoMto[0];
        }else{
            vectorDeUsuario[pos].rfc[2] = 'X';
        }
        vectorDeUsuario[pos].rfc[3] = vectorDeUsuario[pos].nombre[0];
        
        char a_decena, a_unidad;
        a_unidad = (vectorDeUsuario[pos].anio_nac%10) + '0';
        a_decena = ((vectorDeUsuario[pos].anio_nac/10)%10) + '0';
        vectorDeUsuario[pos].rfc[4] = a_decena;
        vectorDeUsuario[pos].rfc[5] = a_unidad;
        
        if(vectorDeUsuario[pos].mes_nac < 10){
            vectorDeUsuario[pos].rfc[6] = '0';
            vectorDeUsuario[pos].rfc[7] = vectorDeUsuario[pos].mes_nac + '0';
        }else{
            char m_decena, m_unidad;int i=0;
            m_unidad = (vectorDeUsuario[pos].mes_nac%10) + '0';
            m_decena = ((vectorDeUsuario[pos].mes_nac/10)%10) + '0';
            vectorDeUsuario[pos].rfc[6] = m_decena;
            vectorDeUsuario[pos].rfc[7] = m_unidad;
        }
        
        if(vectorDeUsuario[pos].dia_nac < 10){
            vectorDeUsuario[pos].rfc[8] = '0';
            vectorDeUsuario[pos].rfc[9] = vectorDeUsuario[pos].dia_nac + '0';
        }else{
            char d_decena, d_unidad;
            d_unidad = (vectorDeUsuario[pos].dia_nac%10) + '0';
            d_decena = ((vectorDeUsuario[pos].dia_nac/10)%10) + '0';
            vectorDeUsuario[pos].rfc[8] = d_decena;
            vectorDeUsuario[pos].rfc[9] = d_unidad;
        }
        
        srand(time(NULL)); //Generamos número aleatorio en base al tiempo
        vectorDeUsuario[pos].rfc[10] = (rand() % 9) + '0'; //Le indicamos que el numero será entre 0-9
        vectorDeUsuario[pos].rfc[11] = (rand() % 9) + '0';
        vectorDeUsuario[pos].rfc[12] = (rand() % 9) + '0';
    }
    result = vectorDeUsuario[pos].rfc;
    printf("Codigo RFC: %s\n", vectorDeUsuario[pos].rfc);
	return &result;
}

nodo_usuario *
listarusuario_1_svc(int *argp, struct svc_req *rqstp)
{
	static nodo_usuario  result;

	printf("\n --------Invocando a consultar Usuario\n");	 
    int res = consultaVector( *argp);
    printf("\n --------Identificador a buscar \n");
    if (res!=-1){
    result = vectorDeUsuario[res];
    }

	return &result;
}

int consultaVector(int p_cedula){
	int resultado=-1;
	int i ;
	for (i=0 ;  i<5 ; i++){
		if (vectorDeUsuario[i].cedula == p_cedula){
			resultado=i;
			break;
		}	
	}
	return resultado;
}

char vocal_interna(char apellido[30]){
    char vocal = ' ';
    for(int i=0; i<30; i++){
        if(apellido[i] == 'a' || apellido[i] == 'e' || apellido[i] == 'i' || apellido[i] == 'o' || apellido[i] == 'u'||apellido[i] == 'A' || apellido[i] == 'E' || apellido[i] == 'I' || apellido[i] == 'O' || apellido[i] == 'U'){
            vocal = apellido[i];
            break;
        }
    }
    return vocal;
}
